- hosts: all
  become: yes
  tasks:
      - name: Download the driver
        get_url:
            url: http://content.mellanox.com/ofed/MLNX_OFED-4.6-1.0.1.1/MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64.tgz
            dest: /tmp/
            mode: 0744

      - name: Extract
        unarchive:
            src: /tmp/MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64.tgz
            dest: /tmp
            remote_src: yes

      - name: Install the driver
        shell: |
            ./mlnxofedinstall --force
        args:
            chdir: /tmp/MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64/

      - name: Restart the driver
        shell: |
            /etc/init.d/openibd restart

      - name: Remove the extracted files
        file:
          path: /tmp/MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64
          state: absent

      - name: Remove the downloaded file
        file:
          path: /tmp/MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64.tgz
          state: absent
